# development:
#   secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

# test:
#   secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

# production:
#   secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>


# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e5ad43b249de9936ca7742ebddd88368ebaa92ef1b1a4f93d9d07af6aa596d34e19fac90680e7ff53e128bb5494806d701d739333d02844b3e8ce72217b385e

test:
  secret_key_base: 672a567680fbce76c8ec6f7450280e506e68eb1b0a7b26a842e9c90800c2adfbfa139d41477cf1f4b9078dd9c30886457355376ea76409616df5e2f2844976c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
